# Generated by Django 3.1 on 2021-08-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210712_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='дата создания фильма'),
        ),
    ]
